- Project.toml
Updates DynamicPPL to have significantly less restrictive compatibility with AbstractMCMC, since the things that DynamicPPL uses are very core to AbstractMCMC and are unlikely to change pre-`AbstractMCMC@1.0`.
> Updated AbstractMCMC compat

- src/compiler.jl
The warning in https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/380 seems to be related to https://github.com/TuringLang/Turing.jl/blob/7cd1800905d51e9cd4f2db5072b96a79e9c6c74f/src/core/compiler.jl#L404-L443.
> Avoid method redefinition

- src/DynamicPPL.jl
- src/compiler.jl
- src/contexts.jl
- src/model.jl
- src/prob_macro.jl
- src/utils.jl
- src/varinfo.jl
- test/compiler.jl
Implements what I proposed in #45.  Surprisingly, I couldn't find any problems yet.
The main change is that
```julia
ex = quote
function $outer_function($(args...))
function $inner_function(
$vi::DynamicPPL.VarInfo,
$sampler::DynamicPPL.AbstractSampler,
$ctx::DynamicPPL.AbstractContext,
$model
)
$unwrap_data_expr
DynamicPPL.resetlogp!($vi)
$main_body
end
return DynamicPPL.Model($inner_function, $args_nt, $model_gen_constructor)
end
$model_gen = $model_gen_constructor
end
```
becomes 
```julia
model_type = :(DynamicPPL.Model{$(QuoteNode(model_function))})
defaults = gensym(:defaults)
ex = quote
function ($model::$model_type)(
$vi::DynamicPPL.VarInfo,
$sampler::DynamicPPL.AbstractSampler,
$ctx::DynamicPPL.AbstractContext,
)
$unwrap_data_expr
DynamicPPL.resetlogp!($vi)
$main_body
end …
```
> Refactor ModelGen and nested closures

- .travis.yml
Should we drop, e.g., Julia 1.1?
> Run CI tests on Julia 1.4

- src/compiler.jl
- src/context_implementations.jl
- src/model.jl
- src/varname.jl
Implements what I proposed in #46.  Each `tilde` or `dot_tilde` call becomes `(dot)_tilde_{assume,observe}`, respectively, depending on position.  And particularly, the varname and indices are also passed in for observations of non-literals. 
These additional arguments are just ignored by default, which makes the changes backwards-compatible. 
Additionally, I changed the way assume/observed is distinguished by the `@preprocess` macro, which is now `@isassumption` and does return a boolean.  Thus the dispatch on tuple types becomes unnecessary.
> Split up tilde functions based on usage

- src/prob_macro.jl
At the moment `_setval!(varinfo, chain)` will fail because `chain` does not support element-wise string-indexing, e.g. `"y[1]"`, but `chain` does support `Symbol("y[1]")`. Therefore I've just changed it to use symbol- instead of string-indexing.
> Fixed _setval! to work with vector-indices

- src/compiler.jl
- src/prob_macro.jl
- src/utils.jl
- src/varname.jl
Fixes the error
```julia
ERROR: LoadError: LoadError: LoadError: UndefVarError: Model not defined
Stacktrace:
[1] top-level scope at /home/david/.julia/packages/DynamicPPL/e9MX7/src/compiler.jl:449
[2] include(::String) at ./client.jl:439
[3] top-level scope at /home/david/.julia/dev/Turing/test/test_utils/AllUtils.jl:7
[4] include(::String) at ./client.jl:439
[5] top-level scope at /home/david/.julia/dev/Turing/test/runtests.jl:9
[6] include(::String) at ./client.jl:439
[7] top-level scope at none:6
in expression starting at /home/david/.julia/dev/Turing/test/test_utils/models.jl:2
in expression starting at /home/david/.julia/dev/Turing/test/test_utils/AllUtils.jl:7
in expression starting at /home/david/.julia/dev/Turing/test/runtests.jl:9
ERROR: Package Turing errored during testing
``` …
> Fix error `Model not defined`

- src/DynamicPPL.jl
- src/compiler.jl
- src/context_implementations.jl
- src/distribution_wrappers.jl
- src/varinfo.jl
- src/varname.jl
- test/Turing/inference/AdvancedSMC.jl
- test/Turing/inference/Inference.jl
- test/Turing/inference/ess.jl
- test/compiler.jl
- test/runtests.jl
- test/varinfo.jl
Implements the changes discussed in #49: make `VarName` use a tuple of tuples instead of a string for the indexing value.  For that, I mostly reused the existing implementations of `@vinds` and `@vsym`.
While at that, I also refactored the methods realing to `VarName` a bit and moved some leftovers to their right place in `varname.jl`.
Updating all the rest of the code base and the tests is still to be done.
> Refactor VarName

- src/DynamicPPL.jl
- src/compiler.jl
- src/model.jl
- src/varinfo.jl
- test/Turing/Turing.jl
- test/Turing/contrib/inference/dynamichmc.jl
- test/Turing/contrib/inference/sghmc.jl
- test/Turing/core/Core.jl
- test/Turing/core/ad.jl
- test/Turing/core/compat/zygote.jl
- test/Turing/inference/Inference.jl
- test/Turing/inference/ess.jl
- test/Turing/inference/hmc.jl
- test/Turing/inference/mh.jl
- test/independence.jl
- test/varinfo.jl
As can be seen in https://github.com/TuringLang/DynamicPPL.jl/pull/50#issuecomment-611088486, the output of `model()` can be quite surprising if no return statements are specified in the model definition. One possible solution to the problem that is implemented in this PR is to always return `nothing` as a fallback. An alternative would be to return the `VarInfo` object as a fallback but that might be not completely user-friendly since it might not be clear how to handle or analyse it.
Additionally, currently `logp` is reset both in the default evaluation function and in `runmodel!`, so basically `model(vi)` and `runmodel!(vi)` are doing the same thing currently apart from adjusting `eval_num`. I removed the `resetlogp!` statement in the evaluation function to allow for greater …
> Less surprising model return values

- src/compiler.jl
- src/utils.jl
- src/varname.jl
- test/compiler.jl
- test/utils.jl
This PR contains the part of https://github.com/TuringLang/DynamicPPL.jl/pull/64 that fixes https://github.com/TuringLang/DynamicPPL.jl/issues/62.
> Do not modify interpolated expressions

- src/varinfo.jl
Currently, a `VarInfo` prints to a huge blob showing all kinds of stuff.  Which is useful on its own in the REPL, but not as part of another printed structure.
I moved that version to `show(::IO, ::MIME"text/plain", ::UntypedVarInfo)`, and added a dummy replacement
```julia
Base.show(io::IO, vi::UntypedVarInfo) = print(io, "VarInfo of ", vi.metadata.vns)
```
Please suggest what things should actually printed in the short version.
> Add shorter non-display printing of VarInfo

- src/compiler.jl
Somehow `replace_tilde!` reappeared although it's not needed anymore.
> Remove `replace_tilde!`

- src/varname.jl
- test/compiler.jl
Fix error on Julia master since `replace_ref_end!` was removed in https://github.com/JuliaLang/julia/pull/35289.
> Use `replace_ref_begin_end!` on Julia >= 1.5.0-DEV.666

- src/varinfo.jl
Looks like I couldn't link a `VarInfo` from `SampleFromPrior` without this, and wanted to see if it was an appropriate fix to add to DynamicPPL. If not, any tips on the better solution?
> Allow linking for SampleFromPrior

- src/compiler.jl
- src/context_implementations.jl
Seems like I'm too late to veto the release, but anyway...
The PR changes the tilde functions used in the generated code to include `acclogp!`, and always just return the sampled value (instead of sometimes the logp, sometimes the logp and the value).  This is in light with the now consistent behaviour of making tildes always return their value, and cleans up the generated code a bit.
It shouldn't make any difference to the outside.  The `[dot_]tilde_{assume,observe}` functions were only added recently in #53 and aren't really part of the public interface -- `tilde` and `dot_tilde` work as before.
> Make tilde_{assume,observe} functions behave more uniformly

- src/context_implementations.jl
- src/utils.jl
- src/varinfo.jl
- test/varinfo.jl
This PR fixes the SampleFromUniform code. SampleFromUniform is only useful in initializing the HMC state. This means that:
1. A new value should always be sampled overwriting the existing values in `VarInfo` which may have come from `SampleFromPrior`, and
2. The `"trans"` flag should be set to `true` because we are not sampling in the support of the random variables' distributions.
This PR also fixes the uniform distribution's support as per @xukai92's suggestion.
> Fix SampleFromUniform

- src/varinfo.jl
- test/varinfo.jl
While working on https://github.com/TuringLang/Turing.jl/pull/1242, I noticed that initially `getlogp(vi)` (where `vi` was initialized as `VarInfo()`) returned `0.0` but subsequently after calling `resetlogp!(vi)` it actually returned `0`. The reason is two-fold: first, `vi.logp` is initialized as a reference to a Real number if not specified explicitly, and then `resetlogp!` is implemented as `resetlogp!(vi) = (vi.logp[] = 0)` which does not perform any conversion to floating point numbers in this case.
I changed both the initialization and `resetlogp!`. I assume there were reasons for not concretely type `vi.logp` as default (maybe because of AD?) - however, all tests of Turing passed locally with this PR.
> Make `logp` concretely typed by default and respect types in `resetlogp!`

- Project.toml
- src/DynamicPPL.jl
- src/context_implementations.jl
- src/sampler.jl
- src/utils.jl
- test/runtests.jl
- test/sampler.jl
- test/varinfo.jl
This PR enables sampling from the prior and with the uniform initialization.
Unfortunately, I have no idea what distributions we expect with the uniform initialization - I studied the code in utils.jl, but I'm a bit confused why we don't just sample from the normal and inverse gamma prior - shouldn't only `TransformDistribution`, `SimplexDistribution`, and `PDMatDistribution` be initialized with a different algorithm? So the test for the uniform initialization has to be adjusted to the correct expected values.
> Fix SampleFromUniform and implement AbstractMCMC interface for SampleFromPrior and SampleFromUniform

- src/distribution_wrappers.jl
I noticed there wasn't a `minimum` or `maximum` implementation for `NoDist`, so I added them.
> Add minimum/maximum for NoDist

- .github/workflows/DynamicPPL-CI.yml
- Project.toml
- src/DynamicPPL.jl
- src/compiler.jl
- src/context_implementations.jl
- src/utils.jl
- test/compiler.jl
- test/varinfo.jl
This PR includes the proper implementation of the idea discussed in https://github.com/TuringLang/DynamicPPL.jl/issues/79#issuecomment-619926597.
It's not clear from the discussion that we've had so far that we actually want to implement thread-safe accumulation of log probabilities in this way (BTW notice that this will only allow to use multiple threads when looping over observations since many more parts than just accumulating log probabilities are not threadsafe when sampling variables). The advantages of the approach in this PR is that it does not modify the implementation of `VarInfo` and hence does not break any code that operates on `VarInfo`. However, accessing the current log probability inside of the model would be a bit more cumbersome, it could be accessed by `sum(_logps)` …
> Make accumulation of log probabilities thread-safe

- src/compiler.jl
- test/compiler.jl
Now something like the following works:
```julia
julia> using DynamicPPL, Distributions
julia> """
demo(x)
This is a demo model.
"""
@model function demo(x)
m ~ Normal()
x ~ Normal(m, 1)
return m
end
demo
help?> demo
search: demo denominator ReadOnlyMemoryError widemul StridedMatrix DenseMatrix divrem code_llvm @code_llvm StridedVecOrMat DimensionMismatch DenseVecOrMat
demo(x)
This is a demo model.
julia> m = demo(1)
Model{var"###evaluator#307",(:x,),Tuple{Int64},(),ModelGen{var"###generator#308",(:x,),(),Tuple{}}}(##evaluator#307, (x = 1,), ModelGen{var"###generator#308",(:x,),(),Tuple{}}(##generator#308, NamedTuple()))
julia> m()
-0.2797280925807616
```
> Docstring for models

- src/compat/ad.jl
- src/threadsafe.jl
- test/compat/ad.jl
This PR fixes Zygote support in the branch `fixes_threaded`. It currently does some type piracy to define an adjoint for `nthreads` and `threadid`. I will make a PR to Zygote with these now, then they can be removed from here when the PR is merged and released.
> Fix Zygote support

- src/context_implementations.jl
`ambiguity_error_msg` is defined in Turing but used in DynamicPPL. One reason more to get rid of Turing in the tests :smile: 
I wanted to add some tests but it's a bit unclear to me what a good example what you be and why we actually want to throw this exception.
> Fix undefined method

- src/compiler.jl
- test/compiler.jl
This PR addresses the problem discussed in https://github.com/SciML/DiffEqBayes.jl/pull/158#issuecomment-626139149 and allows to disable the warnings about internal variable names, similar to the export switch for `@deprecate`.
With this PR it is possible to change
```julia
julia> @model function test()
x ~ Normal(0, 1)
global lp = getlogp(_varinfo)
y ~ Normal(x, 1)
end
┌ Warning: you are using the internal variable _varinfo
└ @ DynamicPPL /home/david/.julia/dev/DynamicPPL/src/compiler.jl:180
ModelGen{var"###generator#341",(),(),Tuple{}}(##generator#341, NamedTuple())
```
to
```julia
julia> @model function test()
x ~ Normal(0, 1)
global lp = getlogp(_varinfo)
y ~ Normal(x, 1)
end false
ModelGen{var"###generator#331",(),(),Tuple{}}(##generator#331, NamedTuple())
```
to suppress the …
> Allow to disable warnings

- bors.toml
Just cherry picked the commit in https://github.com/TuringLang/DynamicPPL.jl/pull/109 that fixes the bors status for Github actions.
> Fix bors status

- test/Turing/Turing.jl
- test/Turing/contrib/inference/dynamichmc.jl
- test/Turing/contrib/inference/sghmc.jl
- test/Turing/core/Core.jl
- test/Turing/core/ad.jl
- test/Turing/core/compat/reversediff.jl
- test/Turing/core/container.jl
- test/Turing/inference/AdvancedSMC.jl
- test/Turing/inference/Inference.jl
- test/Turing/inference/ess.jl
- test/Turing/inference/gibbs.jl
- test/Turing/inference/hmc.jl
- test/Turing/inference/mh.jl
- test/Turing/stdlib/distributions.jl
- test/Turing/utilities/Utilities.jl
- test/Turing/utilities/stan-interface.jl
- test/Turing/variational/VariationalInference.jl
- test/Turing/variational/advi.jl
This PR syncs Turing with the DPPL tests version of Turing. This is helpful because locally I like to develop both Turing and DPPL simultaneously calling `using Turing` instead of `using .Turing` in the DPPL tests and then at the end I copy and paste the Turing src to the test folder.
> Update Turing src in tests

- .travis.yml
- src/compiler.jl
- src/context_implementations.jl
- src/distribution_wrappers.jl
- src/model.jl
- src/sampler.jl
- src/utils.jl
- test/Turing/inference/AdvancedSMC.jl
- test/Turing/inference/ess.jl
- test/Turing/inference/hmc.jl
- test/Turing/inference/is.jl
- test/Turing/inference/mh.jl
- test/compiler.jl
- test/model.jl
- test/threadsafe.jl
This PR fixes https://github.com/TuringLang/Turing.jl/issues/1260.
TODO:
~- [ ] Fix documentation~
> Use non-global RNGs

- src/varinfo.jl
Implements the fix discussed in #122. 
Additionally, makes the code a bit nicer and leaves out the parentheses for empty varinfos (`VarInfo (0 variables, dimension 0; logp: 0.0)` instead of `VarInfo (0 variables (), dimension 0; logp: 0.0)`).
> Fix empty varinfo printing

- src/varinfo.jl
I noticed `islinked(vi, SampleFromPrior())` isn't allowed due to type constraints. Does this seem like a reasonable fix?
> Allow islinked for SampleFromPrior

- test/varinfo.jl
Added a small test that would have caught #131 .
> Added a small test for different contexts and its interaction with VarInfo

- .github/workflows/CompatHelper.yml
- .github/workflows/TagBot.yml
This PR fixes CompatHelper (there's no need to install Julia, CompatHelper takes care of that) and sets it up for running the CI tests on Github (currently CompatHelper does not run any tests). Moreover, it reduces the frequency of TagBot to once per day to save resources.
~~Someone with sufficient permissions has to follow the steps in https://github.com/bcbi/CompatHelper.jl#122-instructions-for-setting-up-the-ssh-deploy-key and add a private key and a deploy key to make it actually work.~~
Edit: Seems I could fix it.
> Fix CompatHelper and reduce frequency of TagBot

- bors.toml
- src/compiler.jl
- test/compiler.jl
This PR fixes https://github.com/TuringLang/DynamicPPL.jl/issues/106 by defining a model generator with exactly the function signature that the user specified (i.e., all positional arguments and keyword arguments are preserved).
E.g.,
```julia
@model function test1(x, y = 4.0)
x ~ Normal(0, 1)
y ~ Exponential()
end
```
defines the model generator `test1(x, y = 4.0)`, whereas
```julia
@model function test2(x; y = 4.0)
x ~ Normal(0, 1)
y ~ Exponential()
end
```
defines the model generator `test2(x; y = 4.0)`. Thus in the first case one can generate a model with `test1(3.0)` and `test1(3.0, 10.0)` but not `test1(3.0, y = 10.0)`, whereas in the second case one can define a model with `test2(3.0)` and `test2(3.0; y = 10.0)` but not `test2(3.0, 10.0)`.
> Define model generator exactly as specified by the user

- .github/workflows/CompatHelper.yml
- .github/workflows/pullrequest.yml
- README.md
In my opinion, currently bug fixes and new features take too much time to propagate through the Turing ecosystem, leading to open issues about problems that are already fixed but not released etc. I guess it also leads to outdated docs more easily since we don't want to update the publicly accessible docs as long as the new features or syntax are not publicly available.
There was some discussion about adopting ColPrac in @willtebbutt's PR over at Turing (https://github.com/TuringLang/Turing.jl/pull/1348), and I basically just added @willtebbutt's suggestions regarding the dev branch to the README explicitly, so that any possible contributor can spot this deviation from ColPrac.
IMO this could smoothen the development and release process quite a bit, and I'm very much in favour of adopting …
> Add ColPrac guide

- Project.toml
- src/DynamicPPL.jl
- src/deprecations.jl
- src/loglikelihoods.jl
- src/model.jl
- src/varname.jl
- test/Turing/Turing.jl
- test/loglikelihoods.jl
This PR replaces `elementwise_loglikelihoods` with `pointwise_loglikelihoods`, as discussed in https://github.com/TuringLang/MCMCChains.jl/issues/243#issuecomment-706549998.
> Replace `elementwise_loglikelihoods` with `pointwise_loglikelihoods`

- Project.toml
- src/context_implementations.jl
- src/prob_macro.jl
- test/prob_macro.jl
> allow redefinition of inputs in logprob

- Project.toml
- src/context_implementations.jl
In `dot_assume` we update the variable (`left` or `var`) in-place, but this is _also_ done in the model-scope https://github.com/TuringLang/DynamicPPL.jl/blob/tor%2Fremove-redundant-assignments/src/compiler.jl#L313-L322.
This PR simply removes the updates performed in `dot_assume`.
EDIT: I'm stupid. I started from `tor/prefix-fix`, so we first just merge this into that branch and then we take it from there.
> Remove redundant mutations in dot_assume

- Project.toml
- src/compiler.jl
- test/Project.toml
- test/compiler.jl
Currently:
```julia
julia> using DynamicPPL
julia> @model function gdemo6()
m ~ MvNormal(2, 1.0)
[10.0, 10.0] ~ MvNormal(m, 0.5 * ones(2))
end
ERROR: LoadError: "Malformed variable name [10.0, 10.0]!"
Stacktrace:
[1] varname(expr::Expr)
@ AbstractPPL ~/.julia/packages/AbstractPPL/CyEC9/src/varname.jl:258
[2] generate_tilde(left::Expr, right::Expr)
@ DynamicPPL ~/.julia/packages/DynamicPPL/emAbx/src/compiler.jl:258
[3] generate_mainbody!(mod::Module, found::Vector{Symbol}, expr::Expr, warn::Bool)
...
```
This also means that using variables in this manner on the LHS isn't allowed, e.g. observe on something `[x, x]`. 
Therefore, we might as well just treat it as literals. This also make it possible to write `[x, x] ~ ...` where `x` is an argument to the model.
This PR allows this by simply …
> Allow usage of array literals on LHS of `~`

- Project.toml
- src/compiler.jl
- test/compiler.jl
Fixes https://github.com/TuringLang/DynamicPPL.jl/issues/260.
> Better error message for anonymous functions

- src/model.jl
- src/submodel_macro.jl
- test/compiler.jl
This PR is a follow-up on the following discussion: https://github.com/TuringLang/DynamicPPL.jl/pull/309/files#r760070684.
I made a separate PR for this as I felt the discussion regarding this particular change was a bit hidden in all the other changes in that PR + it's not strictly _required_ for #309 to go through.
> Improvements to `@submodel` in #309

- docs/src/api.md
- src/distribution_wrappers.jl
- src/simple_varinfo.jl
- src/test_utils.jl
- test/contexts.jl
- test/loglikelihoods.jl
- test/simple_varinfo.jl
When working on #360 I realized there were quite a few features we're not covering with the models provided in `DynamicPPL.TestUtils`, e.g. `link` and `invlink` are not covered since the current models do not include any constrained variables. This PR adds some additional methods in `DynamicPPL.TestUtils` which ought to be implemented for the models and a more general `test_sampler_on_models`.
EDIT: No need to review this until we've merged #360 but I wanted some of these tests for `SimpleVarInfo` to make sure it works properly.
> Improvements to TestUtils (follow-up from #360)

- Project.toml
- src/varinfo.jl
This PR fixes the performance regressions seen for `Emcee` in https://github.com/TuringLang/Turing.jl/pull/1900.
@yebai @devmotion This should be an easy merge.
> Drop unnecessary `depwarn` + fix Turing tests

- Project.toml
- src/varinfo.jl
- test/linking.jl
- test/runtests.jl
Fixes part of the issues discussed in https://github.com/TuringLang/DynamicPPL.jl/issues/504.
It turns out we forgot to add the `test/linking.jl` to `test/runtests.jl` so we haven't been testing the linking properly :facepalm: This is also fixed here.
> Bugfix for linking

- .gitignore
- Project.toml
- ext/DynamicPPLMCMCChainsExt.jl
- test/ext/DynamicPPLMCMCChainsExt.jl
- test/runtests.jl
There is some functionality in DPPL that dispatches on `chain::AbstractChains` while we are in fact assuming the behavior of `chain::MCMCChains.Chains`.
This PR adds an extension for MCMCChains.jl so that we can specialize further when it makes sense.
In particular, in the case of `generated_quantities(model, chain)` we warn the user if some variables are present in `chain` but not in `model`. This makes sense if all the variables present in `chain` are _parameters_, but less so when we are also working with internal parameters; in such a scenario, the user end up seeing tons of warnings regarding unused variables (which are in fact internal variables of the sampler). In this scenario, it makes sense to specialize further on `MCMCChains.Chains` and call `get_sections(chain, :parameters)` …
> Added extension for MCMCChains

- Project.toml
- src/simple_varinfo.jl
- src/test_utils.jl
`VarInfo` uses `Ref` for its logp-field, partially because it makes us compatible with Zygote.jl; Zygote.jl does support differentiating through mutations of `Ref`, though it's _slow_: https://github.com/FluxML/Zygote.jl/issues/999
By default, `SimpleVarInfo` does not mutate its `logp` field, and so it uses a simple `Real` instead of a `RefValue{<:Real}`. This then works fine with Zygote because no mutation occurs, _until_ we start using threads, in which case we're working with a `Vector{<:Real}` instead of `Vector{<:RefValue{<:Real}}`, as is done by default with `VarInfo`.
This can cause some issues when Julia is started with threads, e.g. https://discourse.julialang.org/t/error-running-museinference-jl-example/103360/4.
This PR adds more testing for `SimpleVarInfo` with `Ref` + a fix …
> Fixes for SimpleVarInfo with `Ref`

- Project.toml
- src/utils.jl
You can see the difference in the docstring I've edited.
This was suggested by @sethaxen  as an alternative, which I quite like:)
The alternative is to flatten the `PDMat` instead, i.e. we return the covariance / correlation matrix represented by the cholesky instead of the cholesky factor itself.
Related discussion: https://github.com/TuringLang/Turing.jl/pull/2071
> Improved `varname_and_value_leaves` for `Cholesky`

- Project.toml
- src/DynamicPPL.jl
- src/varinfo.jl
- test/varinfo.jl
https://github.com/TuringLang/Turing.jl/pull/2096 is failing because the current implementations of `link` and `invlink` ignore the "space" of the sampler.
This PR makes it so that `link` and `invlink` now more closely replicates the behavior of `link!!` and `invlink!!`.
I saw "more closely" because they are still different. The "immutable" versions supports changing the sizes of the underlying storage (which is necessary when we're working with distribution whose dimensionality changes when linking, e.g. `Dirichlet`).
> `link` and `invlink` should correctly work with `Selector` and thus `Gibbs`

- Project.toml
- src/utils.jl
- test/model.jl
See https://github.com/TuringLang/Turing.jl/issues/2102 for issue.
When adding tests for this I noticed that some of the `DEMO_MODELS` are not type-stable (even though they should be). This is probably relate to https://github.com/TuringLang/DynamicPPL.jl/issues/530, but let's defer these to a different PR.
> Fix for type instability when using `LKJChol`

- Project.toml
- src/context_implementations.jl
Follow-up on #565: since `acclogp_assume!!` and `acclogp_observe!!` are meant to allow very fine control over how these logpdfs are accumulated, we should IMO try our best to find a context which overloads the behavior of `acclogp_assume!!` and `acclogp_observe!!` rather than just immediately going to the default `assume!!` (which is what do atm).
Hence this PR.
> Defer `acclogp_assume!!` and `acclogp_observe!!` to child context

- Project.toml
- src/debug_utils.jl
- test/debug_utils.jl
@sunxd3 pointed out that we should be using `subsume` rather than equality when checking whether a varname has been seen in the model already (https://github.com/TuringLang/Turing.jl/pull/2218#issuecomment-2100722690).
This PR does exactly that.
> Use `subsume` when checking for repeated varnames

- Project.toml
- src/debug_utils.jl
- test/debug_utils.jl
> Fix for `check_model` on arrays with `undef`

- Project.toml
- src/DynamicPPL.jl
- test/runtests.jl
#604 removed these two macros, but this will just result in ambiguous errors for lots of users (this feature has been displayed in the Turing.jl docs and we know there are people using it) without telling them anything about why the changes was made.
This PR makes them instead error, providing some information on where to find discussion + how to "replace" some of its functionality.
> Added back `prob` and `logprob` macros

- src/model.jl
- test/model.jl
Addresses https://github.com/TuringLang/Turing.jl/issues/2182
The earlier
```
function AbstractPPL.evaluate!!(model::Model, args...)
return evaluate!!(model, Random.default_rng(), args...)
end
```
could lead to infinite recursion. Restricting the types of the varargs solves that.
I would have wanted to rework the method definitions of `evaluate!!` more generally because I find it hard to understand what all the valid ways of calling it are. I thought about it for a bit and couldn't come up with a good solution though, so maybe later.
> Stricter types for evaluate!! methods

- src/context_implementations.jl
Related to https://github.com/TuringLang/Turing.jl/pull/2290
This PR fixes 4 of the following method ambiguities (which arise when testing Turing, but are probably better resolved here):
```
Ambiguity #1
dot_tilde_assume(rng, context::AbstractPPL.AbstractContext, args...) @ DynamicPPL ~/ppl/dppl/src/context_implementations.jl:294
dot_tilde_assume(context::Turing.Experimental.GibbsContext, right, left, vns, vi) @ Turing.Experimental ~/ppl/lib/src/experimental/gibbs.jl:77
Possible fix, define
dot_tilde_assume(::Turing.Experimental.GibbsContext, ::AbstractPPL.AbstractContext, ::Any, ::Any, ::Any)
Ambiguity #2
dot_tilde_assume(rng, context::AbstractPPL.AbstractContext, args...) @ DynamicPPL ~/ppl/dppl/src/context_implementations.jl:294 …
```
> Add AbstractRNG types to fix method ambiguities in Turing

- ext/DynamicPPLMCMCChainsExt.jl
error is: `vn` is not an argument to function `_check_varname_indexing`
also reorder some functions for readability
> Fix an error and reorder some functions in the MCMCChain extension

- ext/DynamicPPLEnzymeCoreExt.jl
Purely a performance optimization
> Mark istrans as inactive

- src/sampler.jl
- test/sampler.jl
Fixes https://github.com/TuringLang/DynamicPPL.jl/issues/672
> `initial_values`: rename theta to flattened_param_vals

- .github/workflows/CI.yml
- .github/workflows/Docs.yml
- .github/workflows/Format.yml
- .github/workflows/IntegrationTest.yml
- .github/workflows/JuliaPre.yml
- Project.toml
- README.md
With setup-julia@v2 we can test `min` (minimum version supported) and `pre` (pre-releases). I think the latter might be more stable and more relevant than testing `nightly`.
> Test pre-releases instead of nightly and update actions

- Project.toml
- src/varinfo.jl
- test/varinfo.jl
This introduces two unrelated changes to `VarInfo`, that came up in the context of https://github.com/TuringLang/Turing.jl/pull/2328:
1. Fix how `gidset` is handled in `merge`
2. Allow pushing new values to `TypedVarInfo` that introduce a new symbol.
The first I think should be uncontroversial. The second is saying that if we have a `TypedVarInfo` that for instance so far only has `vi.metadata = (:x => some_metadata)`, you should still be able to do `push!!(vi, @varname(y), val, dist, gidset)`, and it should introduce a new entry in the `NamedTuple`. This is different from how `TypedVarInfo` is usually created, and might in some cases create `Metadata` objects with quite narrow element types. However, something like this would be needed for cases where new variables may be appear between …
> For VarInfo, fix merge and allow push!!ing new Symbols

- Project.toml
- src/simple_varinfo.jl
- src/varinfo.jl
- test/varinfo.jl
Asking for `subset(vi, VarName[])` used to error, with this it returns an empty `vi` like the original.
Also fixed a couple of mistakes in `subset` for `Metadata`, which were probably inconsequential, but caused the return value to carry with it unnecessary data.
> Allow empty subsets of VarInfos

- Project.toml
- src/simple_varinfo.jl
- src/varinfo.jl
- test/varinfo.jl
Backport #692 and #690, make a new patch release 0.28.6.
I haven't actually run the tests locally, just trying my luck at the end of a work day.
> Backports for 0.28

- Project.toml
- src/utils.jl
Closes #698.
I can confirm that this change fixes the two Turing tests that I listed here https://github.com/TuringLang/Turing.jl/pull/2376#issuecomment-2435695970. It might well fix all the other tests too, since they are giving the same error message.
```julia
using Turing
import ReverseDiff
alg = HMC(0.01, 5; adtype=AutoReverseDiff())
@model function vdemo6()
x = Vector{Real}(undef, 10)
@. x ~ InverseGamma(2, 3)
end
sample(vdemo6(), alg, 10)
@model function vdemo7()
x = Array{Real}(undef, N, N)
@. x ~ [InverseGamma(2, 3) for i in 1:N]
end
sample(vdemo7(), alg, 1000)
```
> Special-case ReshapeTransform for singleton inputs

- src/varinfo.jl
Closes #705.
Note that CI on 1.11 will still fail because of #702. However, the `test/turing/varinfo.jl` tests pass now. Specifically, this test:
https://github.com/TuringLang/DynamicPPL.jl/blob/18af48aee1e6cdac33ebb02166ecdf9fca694c8a/test/turing/varinfo.jl#L264-L265
> Implement custom `getindex` for UntypedVarInfo

- Project.toml
- ext/DynamicPPLMCMCChainsExt.jl
As seen in #702 , `generated_quantities` currently does not work as intented for models with dot-tilde in it. This is due to changes made in #555 to `generated_quantities`, where we started using `fix` instead of `setval_and_resample!`.
Ideally, we should be using `fix` for this, so the changes introduces in #555 were completely reasonable. However, `fix` is still somewhat lacking in support; specifically, it lacks support for `.~`, as outlined in #702. This PR reverts these changes as a hotfix for the resulting bugs.
@mhauru
> Revert to using `setval_and_resample!` in `generated_quantities`

- .github/workflows/CI.yml
cf. https://github.com/TuringLang/Turing.jl/pull/2395
Also just reworks the CI matrix to be clearer
> Update macOS GHA runner to aarch64

- src/debug_utils.jl
- src/test_utils/contexts.jl
- test/debug_utils.jl
#711
To be clear I introduced some of these errors when performing a manual merge, it's just that GitHub decided to merge the PR before I could see the outcome of CI
> Fixing CI from #711

- src/context_implementations.jl
- test/varinfo.jl
Came across these isuse when trying the following with JET.jl 👀 
```julia
julia> using DynamicPPL, Distributions, JET
julia> @model function demo()
x = Vector{Float64}(undef, 2)
x[1] ~ Normal()
x[2] ~ Normal()
return x
end
demo (generic function with 4 methods)
julia> model = demo();
julia> vi = DynamicPPL.typed_varinfo(model);
julia> for vn in keys(vi)
DynamicPPL.set_flag!(vi, vn, "del")
end^C
julia> f, argtypes = DynamicPPL.DebugUtils.gen_evaluator_call_with_types(model, DynamicPPL.typed_varinfo(model), SamplingContext());
julia> report_call(f, argtypes)
═════ 1 possible error found ═════
┌ demo(__model__::Model{…}, __varinfo__::TypedVarInfo{…}, __context__::SamplingContext{…}) @ Main ./REPL[124]:4
│┌ tilde_assume!!(context::SamplingContext{…}, right::Normal{…}, vn::VarName{…}, …
```
> Fixed incorrect calls to `to_linked_internal_transform`

- Project.toml
- src/threadsafe.jl
- src/varinfo.jl
- src/varnamedvector.jl
- test/varinfo.jl
At the moment, this just defers to `getrange(getmetadata(varinfo, varname), varname)`, which extracts the range for `varname` in the corresponding `metadata`.
However, there are two notions of "range" going around here:
1. The range in the _internal_ vector representation which corresponds to `varname`.
2. The range in the _vectorized_ representation of `varinfo` / `metadata` corresponding to `varname`, e.g. as obtained by `values_to(varinfo, Vector)`.
Currently, `getrange` effectively corresponds to (1) in some loose sense (because `getrange(::TypedVarInfo, ::VarName)` actually returns the range used to access the vector representation _inside the corresponding metadata_).
Specifically, consider the following
```julia
@model function demo()
y ~ Normal()
x = Vector(undef, 2)
x[1] ~ …
```
> Introduce `vector_getrange` and `vector_getranges` for `VarInfo`

- .github/workflows/CI.yml
- test/debug_utils.jl
- test/lkj.jl
- test/runtests.jl
- test/sampler.jl
This PR does a bunch of individually minor things, detailed below, but the broad effect is:
- The time taken to run DynamicPPL CI should be cut down to ca. 30 minutes. It was close to 2 hours previously.
- We should get back the green tick so that we can stop force-merging everything.
- Fixes #725
- Separates the tests into two different groups. This was meant as a solution to #725, because the OOM error doesn't happen if you only run the doctests and not the main test suite before it.
- Technically, it's three different groups, but one of the groups will be removed in #733
- Disables fail-fast on the CI matrix, as we don't want half the tests to fail if there's an error in the other half.
- Enables concurrency on the CI job so that pushing a new commit to the same PR cancels CI running …
> Make CI + tests more efficient

- src/varnamedvector.jl
- test/runtests.jl
> Remove extra doctest filters

- Project.toml
- ext/DynamicPPLMCMCChainsExt.jl
- src/values_as_in_model.jl
- test/compiler.jl
- test/model.jl
Closes #765
Specifically, `lhs := rhs` expressions are treated here:
https://github.com/TuringLang/DynamicPPL.jl/blob/665744168066feb654ff2bd783d0ce0b498f431c/src/compiler.jl#L379-L389
This in turn checks for `is_extracting_values(context)`:
https://github.com/TuringLang/DynamicPPL.jl/blob/665744168066feb654ff2bd783d0ce0b498f431c/src/compiler.jl#L394-L404
Currently, this function only returns true for ValuesAsInModelContext, and returns false for every other context.
https://github.com/TuringLang/DynamicPPL.jl/blob/665744168066feb654ff2bd783d0ce0b498f431c/src/values_as_in_model.jl#L40-L45
This PR adds a new boolean field to `ValuesAsInModelContext` which controls whether `is_extracting_values(context)` is true. For `predict`, this field is set to false, so that `lhs := rhs` lines are not …
> Don't include lhs of := in results of predict()

- Project.toml
- src/sampler.jl
- test/sampler.jl
Address https://github.com/TuringLang/DynamicPPL.jl/issues/774 partially.
This only improve the error message, and does not add support for using `OrderedDIct` for initializing.
The error messages are:
* for `Vector{Any}`
```
ArgumentError: `initial_params` must be a vector of type `Union{Real,Missing}`. If `initial_params` is a vector of vectors, please flatten it first using `vcat`.
```
* for `NamedTuple` (keys of `NamedTuple` subsumes some variables in the model, but itself not in the model)
```
ArgumentError: Variable X not found in model, but it subsumes a variable (X[1]) in the model. Please use AbstractVector for initial_params instead of NamedTuple.
```
> Improve error message for `initial_params`

- Project.toml
- docs/src/api.md
- src/contexts.jl
- src/model.jl
- test/contexts.jl
- test/model.jl
This PR:
- in `src/contexts.jl`, removes the methods `AbstractPPL.condition(values, ...)` in favour of directly using the `ConditionContext()` constructor.
This is mainly inspired by Aqua's complaints about how we are pirating `AbstractPPL.{de,}condition` (see #775). I've tested locally and this PR would fix all of the `condition`-related type piracies. But also semantically, I think that `condition` is something you do to a model, not a context (and AbstractPPL's API sort of specifies that too). Since contexts are DynamicPPL-internal, I think it makes sense that we use an different, internal, function to manipulate that.
- likewise, renames `AbstractPPL.decondition(context, ...)` to `decondition_context(context, ...)`. Suggestions for other names welcome!
- shifts the bulk of the …
> Streamline internal de/conditioning interface

- Project.toml
- src/values_as_in_model.jl
- test/model.jl
Looking through the codebase, one realises that `values_as_in_model` only really serves one purpose, which is to extract the values as seen in the model for a given varinfo.
This PR therefore restricts the API of this function to do precisely that (and nothing more). Specifically, it:
- removes the `rng` argument, which would previously cause the function to sample again. (If you really wanted to sample, I think you should sample first and then pass that VarInfo to `values_as_in_model`, i.e. `values_as_in_model(model, true, VarInfo(rng, model)`)
- forces the user to pass a VarInfo argument (previously it would default to generating a blank VarInfo, which would error if `rng` wasn't also provided).
This means that the only signatures allowed are
```
values_as_in_model(::Model, ::Bool, …
```
> Restrict `values_as_in_model` API

- Project.toml
- src/varinfo.jl
- test/varinfo.jl
The diff here is actually much simpler than it looks. The only real change in `src/varinfo.jl` is removing the line `@assert length(vals_left) == length(vals_right)`, in the `if vn in vns_left && vn in vns_right` path. It's just that once you remove that line, you can simplify the surrounding code, because two of the if-paths become exactly identical and the third one nearly so.
I don't see any reason why we couldn't, when merging two metadata objects, merge just the same in the case where the dimension of some variable is different on the left and the right. I asked @torfjelde and he couldn't think of a reason either, but if someone else knows why the `@assert` was there in the first place, please say so.
This change would resolve https://github.com/TuringLang/Turing.jl/pull/2472.
> Fix `merge_metadata` for cases where the dimension of the variable changes

- src/varnamedvector.jl
I find the double negatives confusing.
> Clarify is_unconstrained docstring

- HISTORY.md
- src/contexts.jl
- test/contexts.jl
```julia
using DynamicPPL, Distributions
@model function subsubmodel()
x ~ Normal()
end
@model function submodel()
x ~ to_submodel(prefix(subsubmodel(), :c), false)
return x
end
@model function parentmodel()
x1 ~ to_submodel(prefix(submodel(), :a), false)
x2 ~ to_submodel(prefix(submodel(), :b), false)
end
keys(VarInfo(parentmodel()))
```
Previously, the variable names would be `c.a.x` and `c.b.x`. This PR switches the order so that it's `a.c.x` and `b.c.x`, which is more intuitive.
This PR also adds a changelog. I copied the release notes which I wrote for the last few releases.
Targetting the 0.35 branch because this is a breaking change in behaviour.
Closes #786
> Reverse order of prefixing & add changelog

- Project.toml
KernelAbstractions 0.9.32 caused test failures with DynamicPPLJETExt, see here https://github.com/TuringLang/DynamicPPL.jl/pull/781#event-16017866767
I believe 0.9.33 (and specifically https://github.com/JuliaGPU/KernelAbstractions.jl/pull/557) should have fixed this.
Supersedes the CompatHelper PR #783.
> Bump KernelAbstractions to 0.9.33

- docs/src/api.md
- src/logdensityfunction.jl
- test/ad.jl
In this comment https://github.com/TuringLang/DynamicPPL.jl/pull/806#issuecomment-2660084616 I wrote:
> (1) ...
> 
> (2) Would it be possible to combine `LogDensityFunction` + `LogDensityFunctionWithGrad` into a single struct where the adtype is `Union{Nothing,AbstractADType}`. `adtype=nothing` would serve the same purpose as the current `LogDensityFunction`, and `adtype <: AbstractADType` would replace `LogDensityFunctionWithGrad`. One could then have a `setadtype` function which would, well, set the adtype, but also do the gradient preparation step. This would bring us one step closer to having adtypes be part of the model rather than the sampler, cf. https://github.com/TuringLang/AbstractMCMC.jl/pull/158. The idea would be that if the sampler itself carried information about the …
> Remove LogDensityProblemsAD Extension 2

- docs/src/api.md
- src/DynamicPPL.jl
> Export `LogDensityFunction`

- docs/make.jl
- docs/src/api.md
Tested locally and it works.
https://turinglang.org/DynamicPPL.jl/previews/PR822/api/#Predicting
> Fix predict docstring

- benchmarks/Project.toml
- benchmarks/benchmarks.jl
- benchmarks/src/DynamicPPLBenchmarks.jl
- benchmarks/src/Models.jl
Note that this is a PR into #346, not to `main`.
Turns out we can't depend on TuringBenchmarking.jl because of annoying reverse dependency problems, as discussed in #346, hence these changes. I made this by literally copying the code from TuringBenchmarking.jl and removing all the features of it that weren't useful here. I also put in the one-liner that will hopefully make CI run using the current DPPL version rather than getting one from the package repository, and some compat bounds.
> Make benchmarks not depend on TuringBenchmarking.jl, and run `]dev ..`

- Project.toml
- src/abstract_varinfo.jl
- src/simple_varinfo.jl
- src/varinfo.jl
- src/varnamedvector.jl
- test/varinfo.jl
Previously, `subset(vi, vns)` had the variables in the return value ordered according to `vns` and not according to their order in `vi`. This PR makes the order be the same as that in `vi`.
This fixes the issue in https://github.com/TuringLang/Turing.jl/issues/2300#issuecomment-2692445692.
Since the docstring of `subset` previously said that the order was not guaranteed to be the same as `vi`, without saying what the order _would_ be, I've marked this as a patch rather than a breaking release. I think this is debatable, so feel free to debate it.
@torfjelde, was there a particular reason to not do this before, other than no one bothering to implement it?
> Make subset preserve varname ordering in varinfo

- Project.toml
- src/varinfo.jl
- test/varinfo.jl
> Fix for #842

- Project.toml
- src/distribution_wrappers.jl
- src/utils.jl
- src/varinfo.jl
We were always returning `Int`s. This caused a type instability when the transform of a variable depended on whether it was linked or not, and thus sometimes these `Int`s came into the mix and sometimes they didn't. Returning `Int`s was obviously silly for other reasons too.
I haven't added tests. We should generally go through adding `@inferred` tests to many DPPL internals, see #777, but that should be a separate PR.
> Fix zero-type of logjac for ReshapeTransform

- HISTORY.md
> Add a changelog entry for 0.35.4

- HISTORY.md
- Project.toml
- src/abstract_varinfo.jl
- src/sampler.jl
- src/varinfo.jl
- test/model.jl
- test/simple_varinfo.jl
- test/test_util.jl
Closes #795 
As discussed in #795 and also https://github.com/TuringLang/DynamicPPL.jl/pull/793/files#r1936255984 there are many internal DPPL functions which more or less do the same thing. This PR cleans them up a bit.
More comments to be made on the diff.
> Clean up varinfo get/set functions

- HISTORY.md
- Project.toml
- src/compiler.jl
Fixes https://github.com/TuringLang/DynamicPPL.jl/issues/868
The function itself needs to be interpolated, otherwise it will be left to the caller to resolve. This is OK if they have imported DynamicPPL (as used to be the case in Turing 0.36) but now since Turing no longer exports DynamicPPL, `check_dot_tilde_rhs` can no longer be accessed by the user.
I suppose this also guards against users redefining the function themselves 😄
> Interpolate `DynamicPPL.check_dot_tilde_rhs` into macro

- HISTORY.md
- src/varinfo.jl
> Remove `VarInfo(::VarInfo, ::AbstractVector)`

- HISTORY.md
- Project.toml
- src/debug_utils.jl
- test/debug_utils.jl
Closes #887
Open questions:
- Should it warn or error?
- Should it also check for `±Inf`?
> Error on NaN's in `check_model`

- HISTORY.md
- docs/src/api.md
- src/test_utils/ad.jl
- src/transforming.jl
- test/ad.jl
- test/simple_varinfo.jl
This is a followup from yesterday's meeting.
I think this is a breaking change, so merging into minor release...
> Link varinfo by default in AD testing utilities; make test suite run on linked varinfos

- HISTORY.md
- Project.toml
- src/debug_utils.jl
- test/debug_utils.jl
> Fix isnan for NamedTuple distributions

- HISTORY.md
- docs/src/internals/submodel_condition.md
- src/context_implementations.jl
- src/contexts.jl
- src/model.jl
- src/submodel_macro.jl
- test/contexts.jl
- test/submodels.jl
> [!WARNING]  
> **This PR should only be merged after #892**
This PR changes `PrefixContext` to take a `VarName` as its 'prefix' rather than just a symbol. This allows `PrefixContext` to carry more information and therefore lets us _correctly_ prefix variables in submodels: for example,
```julia
@model function inner()
return x ~ Normal()
end
@model function outer()
a = Vector{Float64}(undef, 1)
a[1] ~ to_submodel(inner())
return a
end
only(keys(VarInfo(outer()))) == @varname(a[1].x) # true
```
Note that this change does not affect type stability, because all information about a `VarName` (its symbol and its optic) is contained in its type.
The improvement to the prefixing behaviour follows from https://github.com/TuringLang/AbstractPPL.jl/pull/119 and …
> Make PrefixContext contain a varname rather than symbol

- HISTORY.md
- docs/Project.toml
- docs/make.jl
- docs/src/api.md
- docs/src/internals/submodel_condition.md
- src/compiler.jl
- src/context_implementations.jl
- src/contexts.jl
- src/model.jl
- src/submodel_macro.jl
- src/utils.jl
- test/contexts.jl
- test/runtests.jl
- test/submodels.jl
This PR closes #857, i.e., gives users sensible ways of conditioning and fixing variables in submodels. To aid in understanding this, it also adds a long piece of documentation ([**PREVIEW HERE**](https://turinglang.org/DynamicPPL.jl/previews/PR892/internals/submodel_condition/)) explaining the design.
In the table below I compare the time taken for `_evaluate!!(model, ...)` on `breaking` (the base branch) and `py/submodel-cond` (HEAD of this PR). For good measure, the followup PR #896 is also benchmarked.
The model tested comprises `m` submodels, all of which contain `n` assumed variables. All times are in µs.
<details>
<summary>Profiling code (click to expand)</summary>
```julia
using DynamicPPL, Distributions, Chairmarks
using Plots
@model function inner(n)
xs = Vector{Float64}(undef, …
```
> Fix `condition` and `fix` in submodels

- HISTORY.md
- Project.toml
- src/context_implementations.jl
In Turing.jl v0.37, when a Gibbs sampler is used without specifying component samplers for all variables, the variables without samplers are sampled once at the beginning and don't ever move from there. See https://github.com/TuringLang/Turing.jl/issues/2536.
This patch is required to preserve that behaviour - without this patch it will throw a MethodError as it was trying to look for the newly added method. Specifically it was this line in Turing.jl that was calling the missing method https://github.com/TuringLang/Turing.jl/blob/fc32e10bc17ae3fda4d7e825b6fde45dc7bdb179/src/mcmc/gibbs.jl#L162-L168
Should hopefully be simple enough to approve -- though I'm very much not a fan of how the N optional arguments force us to define 2^N methods, and it may be worth thinking about how to deal with …
> Implement missing tilde_assume method

- src/compiler.jl
- src/values_as_in_model.jl
- test/compiler.jl
- test/contexts.jl
> Implement values_as_in_model using an accumulator

- Project.toml
- src/test_utils/ad.jl
The docstrings don't list the fields of the return types. This fixes it.
Needs a patch bump so that the 'stable' version of the docs has this info.
> Add fields to docstring for AD test utils

- HISTORY.md
- Project.toml
- src/DynamicPPL.jl
- src/bijector.jl
- test/bijector.jl
- test/runtests.jl
This moves the `bijector` specialization that extracts a bijector from a DynamicPPL `Model`, which was in `Turing.jl`
> Move `bijector(dynamicpplmodel)` from Turing.jl

- HISTORY.md
- Project.toml
- src/debug_utils.jl
- src/varinfo.jl
- test/varinfo.jl
Closes #918 (at least on the DPPL side; there are more things to fix on the Turing side).
```julia
using DynamicPPL, Distributions
@model e(x) = x ~ Normal()
vi = VarInfo(e(1.0))
vi[:]
```
Before this PR, this would error. After this PR, it returns an empty vector.
Interestingly, I think the tests were meant have caught this, but they didn't because varinfos were being mutated (see comment below).
> Fix `varinfo[:]` for empty varinfo

- HISTORY.md
- Project.toml
- src/test_utils/ad.jl
This is necessary for https://github.com/TuringLang/Turing.jl/issues/2307 because AD in sampling is run with a SamplingContext, not a DefaultContext. Thus to properly test AD there we need to be able to specify a context.
> Allow specifying context in AD testing

- test/integration/enzyme/main.jl
This makes Enzyme happy enough to start an attempt at doing AD. It still fails (on DPPL 0.37), but that's already been reported upstream.
Once it starts passing, though, I'll need to benchmark it to see whether the closure is better or not.
> Add `Const` annotation for Enzyme

- test/varinfo.jl
Julia 1.12 improved the error message obtained when trying to access the field of a NamedTuple that didn't exist:
(1.11)
```julia
julia> (; a=1).b
ERROR: type NamedTuple has no field b
Stacktrace:
[1] getproperty(x::@NamedTuple{a::Int64}, f::Symbol)
@ Base ./Base.jl:49
[2] top-level scope
@ REPL[1]:1
```
(1.12)
```julia
julia> (; a=1).b
ERROR: FieldError: type NamedTuple has no field `b`, available fields: `a`
Stacktrace:
[1] getproperty(x::@NamedTuple{a::Int64}, f::Symbol)
@ Base ./Base_compiler.jl:54
[2] top-level scope
@ REPL[1]:1
```
This PR fixes a test that was checking the error message being thrown.
> Fix missing field tests for 1.12

- HISTORY.md
- Project.toml
- docs/src/api.md
The specific method `returned(::Model, ::MCMCChains.Chains)` wasn't documented, even though this is probably the primary usage of `returned`. This fixes it.
Bumped patch so that the `stable` version of the online docs can be updated (otherwise it'll only live in the `dev` docs).
> Improve returned() documentation

- HISTORY.md
- docs/src/api.md
- src/test_utils/ad.jl
- test/ad.jl
This PR makes some fairly overdue improvements to the API of `DynamicPPL.TestUtils.AD.run_ad`.
**`rng` argument**
A `rng` keyword argument is provided to make it easier to seed the parameters used for running AD. Previously, if you wanted to make sure that two calls to `run_ad` used the same parameters (but you didn't care _what_ parameters they were, just that they were the same!), you had to do:
```julia
rng = Xoshiro(468)
v = DynamicPPL.link(VarInfo(rng, model), model)
xs = v[:]
run_ad(model, adtype1; varinfo=v, params=xs)
run_ad(model, adtype2; varinfo=v, params=xs)
```
Now you can do:
```julia
run_ad(model, adtype1; rng=Xoshiro(468))
run_ad(model, adtype2; rng=Xoshiro(468))
```
I made `rng` a keyword argument rather than a positional argument because I consider …
> Improve API for AD testing

- src/test_utils/models.jl
- test/compiler.jl
- test/varinfo.jl
> issue 737 and issue 789

- src/varinfo.jl
Regardless of the outcome of our discussion in #999, I figure we should definitely fix this.
> Fix behaviour of `set_retained_vns_del!` for `num_produce == 0`

- HISTORY.md
- src/test_utils/ad.jl
`run_ad(...; benchmark=true)` used to benchmark `logdensity` and `logdensity_and_gradient`, then take the ratio and return that.
This PR makes it return both benchmark results because, I mean, why not? We already have this information.
There is a bit of dangerous scope creep here in that this function is turning into a replacement for TuringBenchmarking. (Note it can't benchmark the primal alone without a gradient though so it's still not the same.)
But I think it's still useful to know both figures separately. For example, in the CI benchmarks table, we tabulate both times.
Unfortunately I attempted to change the CI benchmark setup to use the new functionality #1002 and promptly got bitten by the bug in #1001. So this PR doesn't change that, not for now, at least.
> Make `DynamicPPL.TestUtils.run_ad` return both the primal and gradient benchmarks

- HISTORY.md
- Project.toml
- ext/DynamicPPLMooncakeExt.jl
`@zero_adjoint` only works for reverse-mode, the replacement is `@zero_derivative` which works for both forwards- and reverse-mode. See https://chalk-lab.github.io/Mooncake.jl/stable/developer_documentation/internal_docstrings/#Mooncake.@zero_adjoint-Tuple{Any,%20Any}
This is required because `Mooncake.TestUtil.test_rule` by default now tests both forwards- and reverse-mode, so to get the following test to pass we need to change the original definition.
https://github.com/TuringLang/DynamicPPL.jl/blob/6742812d664beb0a6e30ff56c005941ea4bd8fab/test/ext/DynamicPPLMooncakeExt.jl#L1-L5
> Fix MooncakeExt for 0.4.147

- src/default_accumulators.jl
`default_accumulators()` no longer needs an integer type because it was only used for num_produce which is now gone.
This is too trivial a change so I won't bother making a release
> Remove unneeded argument from default_accumulators()

- src/model_utils.jl
- src/test_utils.jl
- src/test_utils/sampler.jl
- test/contexts.jl
- test/model.jl
- test/model_utils.jl
actually the horrific thing is that `DynamicPPL.varname_leaves` still works because in DynamicPPL there's a wholesale `using AbstractPPL` which brings it into scope. this PR is therefore not really fixing any error but just makes it look better
> tidy occurrences of varname_leaves as well

- HISTORY.md
- src/threadsafe.jl
- src/varinfo.jl
- test/varinfo.jl
InitContext made it redundant.
Could now change the whole `flags` structure to not be a dict, but might not be worth it if we could just switch over to VarNamedVector.
> Delete the `"del"` flag

- src/contexts/init.jl
- src/sampler.jl
- test/sampler.jl
Currently on `breaking`, `initial_params` has to be specified as an `AbstractInitStrategy`. This PR makes it such that:
- `NamedTuple` and `AbstractDict{<:VarName}` are also allowed, they get wrapped in `InitFromParams` with an info message encouraging people to upgrade instead;
- `Vector` errors with a link to [the docs telling people how to upgrade](https://turinglang.org/docs/usage/sampling-options/#specifying-initial-parameters).
> Allow more flexible `initial_params`
